apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
spec:
  defaultRoute: true
  managementState: Managed
  routes:
    - name: public-routes
      hostname: {{ .Values.global.hostname }}
    #   secretName: {{ .Values.global.registryDomainSecret }}
