kind: ConfigMap
apiVersion: v1
metadata:
  name: config-dev-conf
data:
  dev.conf: |
    resolver            dns-default.openshift-dns.svc;

    map $request_uri $proxypass_dev {
        hostnames;
        default                                                 0;
        ~^/app/mc/asp/srch/(.*)$                                http://mcasps-authorized-service-provider-search.sbms-mc-mcasps-dev.svc.cluster.local:8080;
        ~^/app/mc/asps/srch/(.*)$                               http://mcasps-authorized-service-provider-search.sbms-mc-mcasps-dev.svc.cluster.local:8080;
        ~^/app/mc/gta-atg/(.*)$                                 http://mcg-mc-gravity-calculator.sbms-mc-mcg-dev.svc.cluster.local:8080;
        ~^/app/cb/can(/(.*)|)$                                  http://cb-can.can-cb-ca-number-dev.svc.cluster.local:8080;
    }

    map $uri $rewrite_dev {
        default                                          0;
        ~^/app/mc/asps/srch/(.*)$                        /$1;
    }

    map $request_uri $bodysize_dev {
        default       0;    
    }
    server {
        server_name dev.ised-isde.canada.ca;
        listen 8080;
        client_max_body_size 100M;

        gzip on;

        #=== Generic Location =============================================================
        location / {
            if ($proxypass_dev = 0) {
                return 302 https://www.ic.gc.ca;              
            }
            
            proxy_pass         $proxypass_dev;
            if ($rewrite_dev) {
                rewrite            ^/(.*)$ $rewrite_dev break;
            }
            include            /opt/app-root/etc/nginx.d/proxy.conf;
            # if ($bodysize_dev) {
            #     client_max_body_size  $bodysize_dev;
            # }
        }