kind: ConfigMap
apiVersion: v1
metadata:
  name: config-nginx-conf
data:
  nginx.conf: |
    worker_processes 1;

    events {
        worker_connections 1024;
    }

    http {
        
        proxy_http_version 1.1;
        
        sendfile on;

        server_tokens off;

        include     /opt/app-root/etc/nginx.d/dev.conf;
        include     /opt/app-root/etc/nginx.d/intranet-dev.conf;
        include     /opt/app-root/etc/nginx.d/gc-internal-dev.conf;
        include     /opt/app-root/etc/nginx.d/033gc-dev.conf;
        
        include     /opt/app-root/etc/nginx.d/uat.conf;
        include     /opt/app-root/etc/nginx.d/intranet-uat.conf;
        include     /opt/app-root/etc/nginx.d/gc-internal-uat.conf;
        
        include     /opt/app-root/etc/nginx.d/qa.conf;
        include     /opt/app-root/etc/nginx.d/intranet-qa.conf;
        include     /opt/app-root/etc/nginx.d/gc-internal-qa.conf;

        include     /opt/app-root/etc/nginx.d/033gc-int.conf;
        include     /opt/app-root/etc/nginx.d/033gc-test.conf;

        log_format main '$proxy_add_x_forwarded_for - $remote_user [$time_local] [$msec] '
          '[$request_time] "$request" $status $body_bytes_sent '
          '"$http_referer" "$http_user_agent"';

        access_log /var/log/nginx/access.log main;
    }
