apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ISED Proxy - non prod
    openshift.io/display-name: ISED Proxy - non prod
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  name: ised-proxy
