apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/hsts_header: max-age=31536000;includeSubDomains;preload
    haproxy.router.openshift.io/ip_whitelist: 0.0.0.0/0
  labels:
    app: {{ .Values.global.applicationName }}
  name: {{ .Values.global.applicationName }}
spec:
  host: dev.ised-isde.canada.ca
  path: http://certificate.ised-certificates:8080/ised-isde.canada.ca-patch.json
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.global.applicationName }}
    weight: 100
  wildcardPolicy: None
