apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.global.applicationName }}
    organization: ised
  name: {{ .Values.global.applicationName }}
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: 8080-tcp
      port: 8080
  selector:
    deploymentconfig: {{ .Values.global.applicationName }}