applications:
  - name: ised-nginx-non-prod
    labels:
      app: ised-nginx-non-prod
    annotations:
      reloader.stakater.com/auto: "true"
    replicas: 1
    specSelectorLabels:
      enabled: true
      app: ised-nginx-non-prod
      deploymentconfig: ised-nginx-non-prod
    specTemplateLabels:
      enabled: true
      app: ised-nginx-non-prod
      deploymentconfig: ised-nginx-non-prod
    containers:
    - name: ised-nginx
      image: ised-nginx:non-prod
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
        protocol: TCP
      - containerPort: 9090
        protocol: TCP
      readinessProbe:
        enabled: true
        failureThreshold: 3
        httpGetPath: /robots.txt
        httpGetPort: 8080
        httpGetScheme: HTTP
        initialDelay: 180
        period: 10
        successThreshold: 1
        timeout: 2
      livenessProbe:
        enabled: true
        failureThreshold: 3
        httpGetPath: /robots.txt
        httpGetPort: 8080
        httpGetScheme: HTTP
        initialDelay: 180
        period: 10
        successThreshold: 1
        timeout: 2
      resources:
        memoryRequest: "100Mi"
        cpuRequest: "50m"
        memoryLimit: "300Mi"
        cpuLimit: "100m"
      env: 
      - name: ENVIRONMENT
        value: non-prod
      - name: ""
        valueFrom:
          secretKeyRef:
            key: ""
            name: ""
      - name: ""
        valueFrom:
          configMapKeyRef:
            name: ""
            key: ""
    volumes:
      enabled: true
      data:
        - name: "config-dev-conf"
          typeName: "config-dev-conf"
          type: "configmap"
          volMountPath: "/opt/app-root/etc/nginx.d/dev.conf"
          volMountSubpath: "dev.conf"
        - name: "config-proxy-conf"
          typeName: "config-proxy-conf"
          type: "configmap"
          volMountPath: "/opt/app-root/etc/nginx.d/proxy.conf"
          volMountSubpath: "proxy.conf"
        - name: "config-robots-deny-all-conf"
          typeName: "config-robots-deny-all-conf"
          type: "configmap"
          volMountPath: "/opt/app-root/etc/nginx.d/robots-deny-all.conf"
          volMountSubpath: "robots-deny-all.conf"
        - name: "config-nginx-conf"
          typeName: "config-nginx-conf"
          type: "configmap"
          volMountPath: "/etc/nginx/nginx.conf"
          volMountSubpath: "nginx.conf"
        - name: "maintenance-page"
          typeName: "maintenance-page"
          type: "configmap"
          volMountPath: "/opt/app-root/www/data/maintenance.html"
          volMountSubpath: "maintenance.html"

        # - name: "name-secret-of-instance"
        #   typeName: "mysecret"
        #   type: "secret"
        #   volMountPath: "volMountPath2"
        #   volMountSubpath: "volMountSubPath2"
    strategy:
      activeDeadline: ""
      type: ""
      maxSurge: ""
      maxUnavailable: ""
      timeout: ""
      interval: ""
      updatePeriod: ""


